# Generated by Django 2.0 on 2017-12-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
